Feature/5 g 28
Taoffy/middle.yandex.praktikum.5g.game pull request #11
Opened 2022-12-30 12:11 UTC by dannysonn

### верстка профиля

2023-01-05 10:51 UTC, antonabaltusov approved these changes

2023-01-09 08:28 UTC, RodionBozhenko approved these changes

2023-01-09 18:18 UTC, Taoffy requested changes

2023-01-09 18:18 UTC, Taoffy commented on packages/client/index.html
> +    <link rel='stylesheet' href='src/pages/Profile/Profile.css'>
Не нужно через html подключать, можно через `tsx` файл все это делать, я скидывал статью про css-модули

2023-01-10 18:01 UTC, merged