Feature/5G-78
Taoffy/middle.yandex.praktikum.5g.game pull request #19
Opened 2023-01-26 16:37 UTC by dannysonn

### Смена данных пользователя

2023-01-29 11:50 UTC, RodionBozhenko submitted a review, later dismissed
В целом все будет работать, все круто. Но почему ты используешь старый редакс? Если есть какая-то конкретная причина, то окей. Но вообще редакс очень устарел из-за того, сколько там приходится писать лишнего кода. Команда редакса давно создала новый его вариант Redux Toolkit. Его использовать намного проще. Намного меньше кода, много крутых фич и не надо оборачивать компоненты в коннект. 
Кроме этого, хочу сказать о работе с формами. Для форм в Реакте лучше всего использовать популярные библиотеки, моя рекомендация это React Hook Form, хотя можно еще рассмотреть Formik, но я не советую.
В общем, нужно всегда "держать руку на пульсе" и использовать стабильные популярные технологии, зарекомендовавшие себя среди программистского сообщества.
Но решать вам как команде, что лучше использовать. Советую эти моменты обсудить командой.
Ссылки на инфу о том почему лучше использовать те инструменты, что я перечислил: 
https://www.shawndsilva.com/blog/web-development/differences-between-redux-and-redux-toolkit-and-why-should-you-upgrade#:~:text=RTK%20is%20a%20Hooks%20based,generated%20Actions%20from%20the%20Reducers
https://www.bigscal.com/blogs/frontend-technology/why-is-react-hook-form-better-than-other-forms/#:~:text=react%2Dhook%2Dform-,Introduction,state%20which%20speeds%20up%20performance.

2023-01-29 15:17 UTC, Taoffy commented
> В целом все будет работать, все круто. Но почему ты используешь старый редакс? Если есть какая-то конкретная причина, то окей. Но вообще редакс очень устарел из-за того, сколько там приходится писать лишнего кода. Команда редакса давно создала новый его вариант Redux Toolkit. Его использовать намного проще. Намного меньше кода, много крутых фич и не надо оборачивать компоненты в коннект. Кроме этого, хочу сказать о работе с формами. Для форм в Реакте лучше всего использовать популярные библиотеки, моя рекомендация это React Hook Form, хотя можно еще рассмотреть Formik, но я не советую. В общем, нужно всегда "держать руку на пульсе" и использовать стабильные популярные технологии, зарекомендовавшие себя среди программистского сообщества. Но решать вам как команде, что лучше использовать. Советую эти моменты обсудить командой. Ссылки на инфу о том почему лучше использовать те инструменты, что я перечислил: https://www.shawndsilva.com/blog/web-development/differences-between-redux-and-redux-toolkit-and-why-should-you-upgrade#:~:text=RTK%20is%20a%20Hooks%20based,generated%20Actions%20from%20the%20Reducers https://www.bigscal.com/blogs/frontend-technology/why-is-react-hook-form-better-than-other-forms/#:~:text=react%2Dhook%2Dform-,Introduction,state%20which%20speeds%20up%20performance.

Приняли решение использовать обычный redux из-за того, что большинство людей в команде не работало еще с проектами на реакте в принципе, показалось, что так будет легче и быстрее, возможно перейдем на тулкит позднее.

2023-01-29 15:25 UTC, Taoffy requested changes

2023-01-29 15:25 UTC, Taoffy commented on packages/client/src/components/pages/Profile/ChangeData/ChangeData.tsx
> +    const form = document.getElementById('change-data');
Так в реакте лучше не делать, здесь есть хук useRef для такого https://ru.reactjs.org/docs/hooks-reference.html#useref

2023-01-29 15:25 UTC, Taoffy commented on packages/client/src/components/pages/Profile/ChangePassword/ChangePassword.module.scss
> +    position: fixed;
Вот только правил это перед демо, не нужно использовать fixed, если в этом нету необходимости, это вырывает элемент из потока документа и с этим могут быть проблемы в дальнейшем. Тут лучше позиционировать все с помощью flex или grid

2023-02-03 06:47 UTC, Taoffy requested changes
У тебя, похоже, не настроен prettier, файлы не отформатированы, попробуй по статье сделать(https://www.alphr.com/use-prettier-vs-code/), стоит еще включить настройку, чтобы prettier работал только когда есть конфиг

2023-02-03 06:47 UTC, Taoffy commented on packages/client/src/components/pages/Profile/ChangeData/ChangeData.tsx
> +import { connect, useDispatch } from 'react-redux'
Не нужно использовать connect, у нас для этого есть хук useSelector, все данные забираются через него

2023-02-03 06:47 UTC, Taoffy commented on packages/client/src/components/pages/Profile/ChangeData/ChangeData.tsx
> +function ChangeData(props: ChangeDataProps) {
Так лучше не писать, нужно всегда деструктурировать пропсы и прописывать их

2023-02-03 06:47 UTC, Taoffy commented on packages/client/src/components/pages/Profile/Profile.tsx
> +function Profile(props: ProfileProps) {
Здесь тоже самое про конект и пропсы

2023-02-03 06:47 UTC, Taoffy commented on packages/client/src/redux/actions.ts
> +export const changeUserData = (userData: UserData) => {
Необязательно все экшены в один файл складывать, можно их разделить или здесь решить мердж-конфликты

2023-02-03 06:47 UTC, Taoffy commented on packages/client/src/redux/types.ts
> +export interface UserData {
Здесь так же в мастере уже есть эти типы

2023-02-06 06:30 UTC, Taoffy requested changes

2023-02-06 06:30 UTC, Taoffy commented on packages/client/src/components/pages/Profile/ChangeData/ChangeData.tsx
> +  const first_name = useSelector((state: Store) => state.app.user.first_name);
Не нужно каждое поле забирать, забирай объект user

2023-02-08 05:46 UTC, Taoffy submitted a review, later dismissed

2023-02-15 16:54 UTC, Taoffy approved these changes

2023-02-15 16:58 UTC, merged