userservise
Taoffy/middle.yandex.praktikum.5g.game pull request #2
Opened 2022-12-25 13:08 UTC by antonabaltusov

### Функционал авторизации

подключил axios
создал класс UserServise  c cooтветствующими методами.
скорее всего надо будет дорабатывать по мере создания страниц.

2022-12-25 15:23 UTC, dmitmokrov reviewed
Общее замечание: где-то есть ; в конце строки, где-то нет. Я все-таки за то, чтобы ; была всегда. Лучше быть уверенным, что ничего не выстрелит тебе в ногу, т.к. если не указывать ; явно, нужно знать некоторые тонкости, когда это можно делать, а когда нет. По идее, это все можно решить на уровне линтера и форматтера кода. Либо модем в чате этот момент обговорить и принять решение, как делаем.

2022-12-25 15:23 UTC, dmitmokrov commented on packages/client/src/core/config/api.config.ts
> +export const serverYandexURL = "https://ya-praktikum.tech/api/v2";
Думаю, из названия переменной можно убрать yandex, просто serverUrl достаточно, + не будет привязки к домену в названии. К тому же если что-то поменяется, тогда придется переименовывать.

2022-12-25 15:23 UTC, dmitmokrov commented on packages/client/src/core/services/UserService.ts
> +type RegistrRequestData = {
Здесь я бы тоже название изменил, непонятно, то ли это опечатка (не хватает буквы 'e' - RegistEr..), то ли это просто сокращение от registration. Но тогда лучше не сокращать.

2022-12-25 15:23 UTC, dmitmokrov commented on packages/client/src/core/services/UserService.ts
> +  async registration(data: RegistrRequestData) {
Методы лучше называть глаголом, т.к. они предполагают действие. Поэтому предлагаю тоже переименовать, например, на signIn и signUp, куда, собственно, запрос и идет

2022-12-25 15:23 UTC, dmitmokrov commented on packages/client/src/core/services/UserService.ts
> +      >('/auth/signup', data)
Под пути предлагаю создать константу или enum, чтобы строки не писать. К тому же будут другие апи, все пути удобно будет хранить в одном месте.

2022-12-25 15:23 UTC, dmitmokrov commented on packages/client/src/core/types/app.d.ts
> +  type UserDTO = {
Из названия непонятно, что значит DTO. Чисто логически можно догадаться, что это поля, которые сервер ожидает. Но лучше переименовать.

2022-12-25 15:23 UTC, dmitmokrov commented on packages/client/src/core/utils/apiHasError.ts
> +  return response && response.reason
Здесь можно ?. опциональную цепочку написать, как я понимаю, т.е. response?.reason просто

2022-12-25 15:23 UTC, dmitmokrov commented on packages/client/src/core/utils/apiTransformers.ts
> +      ? 'https://ya-praktikum.tech/api/v2/resources/' + data.avatar
Путь нужно либо в константу вынести, либо хотя бы использовать константу serverYandexURL как часть пути

2022-12-25 15:23 UTC, dmitmokrov commented on packages/client/src/core/utils/apiTransformers.ts
> +export const transformUser = (data: UserDTO): User => {
Название я бы изменил. Непонятно, что за трансформация происходит. Условно, transformUserDataToClient.

2022-12-25 15:48 UTC, antonabaltusov commented on packages/client/src/core/config/api.config.ts
> +export const serverYandexURL = "https://ya-praktikum.tech/api/v2";
просто я это сделал с учетом того что у нас будет наш апи. надо будет завтра на созвоне это обсудить.

2022-12-27 13:30 UTC, nastydolgova approved these changes, later dismissed

2022-12-29 13:25 UTC, Taoffy requested changes
Стоит поправить названия переменных и методов, про которые писал Дима

2022-12-29 13:25 UTC, Taoffy commented on packages/client/src/core/utils/apiTransformers.ts
> +export const transformUser = (data: UserDTO): User => {
Скорее тут тоже нужно действием описать метод, как пример-getUserData

2022-12-29 17:53 UTC, RodionBozhenko commented on packages/client/src/core/services/UserService.ts
> +  }
Для методов класса в тайпскрипте, необходимых только внутри класса, стоит использовать ключевое слово private перед объявлением метода. Таким образом, метод будет доступен при объявлении других методов класса (как это у тебя и используется), но вызывать этот метод на сущности класса будет запрещено.
Ссылка на документацию: https://www.typescriptlang.org/docs/handbook/2/classes.html#private

2022-12-29 17:56 UTC, RodionBozhenko requested changes
Все гуд, но надо поработать над неймингами, чтобы они четче отображали суть происходящего и в них не было лингвистических ошибок. Согласен со всеми комментариями @dmitmokrov, постарайся переделать код в соответствии с ними. Также оставил коммент о приватных классах.

2023-01-09 08:27 UTC, RodionBozhenko approved these changes, later dismissed

2023-01-09 18:14 UTC, Taoffy submitted a review, later dismissed

2023-01-10 18:00 UTC, Taoffy approved these changes

2023-01-10 18:01 UTC, merged