Feature/5 g 30
Taoffy/middle.yandex.praktikum.5g.game pull request #22
Opened 2023-02-02 18:32 UTC by dannysonn

### Смена пароля пользователя

2023-02-03 06:48 UTC, Taoffy requested changes
Здесь те же замечания, что и в пулл-реквесте с данными

2023-02-06 06:33 UTC, Taoffy requested changes

2023-02-06 06:33 UTC, Taoffy commented on packages/client/src/components/pages/Profile/ChangePassword/ChangePassword.tsx
> +    const formData = new FormData(formEl.current as unknown as HTMLFormElement);
А зачем тут два as?

2023-02-06 06:33 UTC, Taoffy commented on packages/client/src/components/pages/Profile/ChangePassword/ChangePassword.tsx
> +const mapStateToProps = (state: any) => {
Здесь тоже нужно использовать селекторы

2023-02-06 06:33 UTC, Taoffy commented on packages/client/src/components/pages/Profile/Profile.tsx
> +  const [isPopupActive, setPopupActive] = useState(false);
Тоже только юзера забирать

2023-02-06 06:33 UTC, Taoffy commented on packages/client/src/core/services/UserDataService.ts
> +      login: "pavukkkkk",
Логин уже смерджен, надо убрать это

2023-02-06 14:26 UTC, dannysonn commented on packages/client/src/components/pages/Profile/ChangePassword/ChangePassword.tsx
> +    const formData = new FormData(formEl.current as unknown as HTMLFormElement);
иначе тс ругается, не сообразил иначе как можно

2023-02-08 05:46 UTC, Taoffy approved these changes, later dismissed

2023-02-09 07:49 UTC, RodionBozhenko submitted a review, later dismissed

2023-02-23 17:17 UTC, antonabaltusov submitted a review, later dismissed

2023-02-24 09:52 UTC, RodionBozhenko approved these changes, later dismissed

2023-02-27 11:01 UTC, Taoffy submitted a review, later dismissed

2023-03-01 06:10 UTC, Taoffy submitted a review, later dismissed

2023-03-01 06:12 UTC, Taoffy approved these changes

2023-03-01 06:13 UTC, merged