Feature/5G-19
Taoffy/middle.yandex.praktikum.5g.game pull request #24
Opened 2023-02-14 20:16 UTC by dannysonn

###  SSR без роутинга, в роутах можете выставить login как "/", просмотреть код страницы и увидите HTML

2023-02-15 21:30 UTC, RodionBozhenko submitted a review, later dismissed

2023-02-22 17:28 UTC, Taoffy requested changes

2023-02-22 17:28 UTC, Taoffy commented on packages/client/src/App.tsx
> +import './scss/index.scss'
Опять проблемы с prettier, что-то у тебя не так настроено

2023-02-23 17:17 UTC, antonabaltusov approved these changes, later dismissed

2023-02-23 18:54 UTC, Taoffy approved these changes

2023-02-24 09:52 UTC, RodionBozhenko approved these changes

2023-02-25 11:01 UTC, merged