5G-31 & 5G-32
Taoffy/middle.yandex.praktikum.5g.game pull request #25
Opened 2023-02-21 23:02 UTC by dannysonn

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-23 17:17 UTC, antonabaltusov approved these changes, later dismissed

2023-02-24 09:39 UTC, RodionBozhenko commented on packages/client/src/components/AvatarPopup/AvatarPopup.tsx
> +  const dispatch = useDispatch() as any; // Как это типизировать? Как вообще понять как типизировать такие штуки?
Прям как в документации https://redux.js.org/usage/usage-with-typescript#define-typed-hooks. Я не был уверен работает ли этот подход в старом редаксе, который вы используете, так что проверил в codesandbox  и у меня все получилось. Если так не получится типизировать в вашем случае, то дайте знать

2023-02-24 09:50 UTC, RodionBozhenko commented on packages/client/src/components/AvatarPopup/AvatarPopup.tsx
> +      const formData = new FormData() as any; // Как это типизировать? Как вообще понять как типизировать такие штуки?
formData типизировать не надо, эта переменная уже имеет необходимый тип полученный при объявлении переменной через new FormData(). То есть тайпскрипт уже знает какой тип у formData. А для того, чтобы в этой функции Actions.changeUserAvatar(formData) был правильный тип аргумента, надо просто навести мышкой на переменную formData и IDE покажет какой тип вам нужен. И вообще совет при работе с тайпскриптом обращать внимание на эти аннотации от IDE, чтобы понимать какой тип нужен.

2023-02-24 09:51 UTC, RodionBozhenko requested changes
Надо типизировать useDispatch и useSelector как в документации https://redux.js.org/usage/usage-with-typescript#define-typed-hooks

2023-03-01 06:18 UTC, Taoffy requested changes

2023-03-01 06:18 UTC, Taoffy commented on packages/client/src/core/services/UserDataService.ts
>  const api = axios.create({
Api лучше инициализировать отдельно и потом импортить во все сервисы, можно создать в корне клиентской части папку api с соответствующим файлом

2023-03-01 06:18 UTC, Taoffy commented on packages/client/src/core/services/UserDataService.ts
> +      login: 'pavukkkkk',
Это нужно убрать, данные должны быть из формы

2023-03-01 06:20 UTC, Taoffy commented on packages/client/src/core/services/UserDataService.ts
>  const api = axios.create({
Уже есть инициализированное api, можно не создавать
Как я понимаю этот файл вообще удалить нужно, т.к. у нас уже есть регистрация и логин

2023-03-01 18:12 UTC, Taoffy requested changes

2023-03-01 18:12 UTC, Taoffy commented on docker-compose.yml
> +        depends_on:
У тебя что-то совсем мешанина с ветками получается, тут этого не должно быть

2023-03-02 15:20 UTC, Taoffy approved these changes

2023-03-02 15:23 UTC, Taoffy approved these changes

2023-03-02 15:23 UTC, merged