Feature/5 g 35
Taoffy/middle.yandex.praktikum.5g.game pull request #31
Opened 2023-03-09 05:38 UTC by MrToddest

API лидерборда ya-pr

2023-03-11 09:53 UTC, antonabaltusov commented on packages/client/src/api/leaderboardAPI.ts
> +            withCredentials: true,
думаю можно уже не писать строчки эти так как это прописано в создании api

2023-03-11 09:54 UTC, antonabaltusov commented on packages/client/src/api/leaderboardAPI.ts
> +            withCredentials: true,
и в других аналогичных местах

2023-03-12 13:40 UTC, Taoffy requested changes
А почему не интегрировал его? Нужно интегрировать и на страницы, сделать отправку счета и получение списка на странице

2023-03-21 06:48 UTC, Taoffy approved these changes

2023-03-21 06:48 UTC, merged