Feature/5 g 56
Taoffy/middle.yandex.praktikum.5g.game pull request #40
Opened 2023-03-21 19:04 UTC by dannysonn

### Тёмная и светлая темы

2023-03-21 20:00 UTC, antonabaltusov requested changes

2023-03-21 20:00 UTC, antonabaltusov commented on packages/client/src/core/services/UserService.ts
> +      return theme;
лучше сделать возврат через функцию `this.checkAnswer<object>(response);`

2023-03-21 20:00 UTC, antonabaltusov commented on packages/client/src/core/services/UserService.ts
> +      return theme;
в ней если ответ не 200 или 201 то уйдет в catch

2023-03-21 20:00 UTC, antonabaltusov commented on packages/client/src/redux/app-reducer.ts
> +    theme: '',
можно тогда сделать сразу дефолтную строчку light наприме

2023-03-22 07:56 UTC, Taoffy approved these changes, later dismissed

2023-03-22 08:00 UTC, Taoffy approved these changes

2023-03-22 08:03 UTC, merged