5G-73 Добавляет базовые стили всех страниц
Taoffy/middle.yandex.praktikum.5g.game pull request #6
Opened 2022-12-27 18:27 UTC by dmitmokrov

2022-12-27 21:09 UTC, nastydolgova submitted a review, later dismissed

2022-12-28 10:16 UTC, Taoffy requested changes

2022-12-28 10:16 UTC, Taoffy commented on packages/client/src/styles/base.css
> +  box-sizing: border-box;
Зачем задавать одному элементу и потом ниже, если можно задать сразу всем элементам?

2022-12-28 10:16 UTC, Taoffy commented on packages/client/src/styles/base.css
> +  --base-text-color: #000000;
Переменные тоже нужно хранить для всех элементов

2022-12-28 10:19 UTC, dmitmokrov commented on packages/client/src/styles/base.css
> +  box-sizing: border-box;
Это используется для того, чтобы не сломать box-sizing, если подключаются какие-то библиотеки, в которых стили используют content-box значение.

2022-12-28 10:23 UTC, dmitmokrov commented on packages/client/src/styles/base.css
> +  --base-text-color: #000000;
Не понял комментарий. Переменные наследуются, как стили. Поэтому их указывают на верхнем уровне. Если у какого-то элемента нужно ее переопределить, то в стилях этого элемента ее и переопределяют.

2022-12-29 17:27 UTC, RodionBozhenko submitted a review, later dismissed

2023-01-04 15:26 UTC, Taoffy approved these changes, later dismissed

2023-01-10 18:05 UTC, Taoffy approved these changes, later dismissed

2023-01-10 18:07 UTC, Taoffy approved these changes

2023-01-10 18:08 UTC, merged